module.exports = {
  1: 'Chemicals',
  2: 'Paints',
  3: 'Cosmetics and Cleaning Preparations',
  4: 'Lubricants and Fuels',
  5: 'Pharmaceuticals',
  6: 'Metal Goods',
  7: 'Machinery',
  8: 'Hand Tools',
  9: 'Electrical and Scientific Apparatus',
  10: 'Medical Apparatus',
  11: 'Environmental Control Apparatus',
  12: 'Vehicles',
  13: 'Firearms',
  14: 'Jewelry',
  15: 'Musical Instruments',
  16: 'Paper Goods and Printed Matter',
  17: 'Rubber Goods',
  18: 'Leather Goods',
  19: 'Non-metallic Building Materials',
  20: 'Furniture and Articles Not Otherwise Classified',
  21: 'Housewares and Glass',
  22: 'Cordage and Fibers',
  23: 'Yarns and Threads',
  24: 'Fabrics',
  25: 'Clothing',
  26: 'Fancy Goods',
  27: 'Floor Coverings',
  28: 'Toys and Sporting Goods',
  29: 'Meats and Processed Foods',
  30: 'Staple Foods',
  31: 'Natural Agricultural Products',
  32: 'Light Beverages',
  33: 'Wines and Spirits',
  34: 'Smokers’ Articles',
  35: 'Advertising and Business',
  36: 'Insurance and Financial',
  37: 'Building Construction and Repair',
  38: 'Telecommunications',
  39: 'Transportation and Storage',
  40: 'Treatment of Materials',
  41: 'Education and Entertainment',
  42: 'Computer and Scientific',
  43: 'Hotels and Restaurants',
  44: 'Medical, Beauty and Agricultural',
  45: 'Personal and Legal',
};
